export const AGENT_OPERATION_NAMES = [
  'agent.assignForgeScope',
  'agent.assignGoal',
  'agent.create',
  'agent.createFromTemplate',
  'agent.ensureSession',
  'agent.get',
  'agent.list',
  'agent.reminders.cancel',
  'agent.reminders.create',
  'agent.reminders.list',
  'agent.unassignForgeScope',
  'agent.unassignGoal',
  'agent.update',
  'agentTemplate.create',
  'agentTemplate.delete',
  'agentTemplate.list',
  'agentTemplate.update',
] as const;
