export const AGENT_OPERATION_NAMES = [
  'agent.assignForgeScope',
  'agent.assignGoal',
  'agent.create',
  'agent.ensureSession',
  'agent.get',
  'agent.list',
  'agent.reminders.cancel',
  'agent.reminders.create',
  'agent.reminders.list',
  'agent.template.create',
  'agent.template.delete',
  'agent.template.instantiate',
  'agent.template.list',
  'agent.template.update',
  'agent.unassignForgeScope',
  'agent.unassignGoal',
  'agent.update',
] as const;
