export const EXTERNAL_EVENT_OPERATION_NAMES = [
  'externalEvent.agent.listSubscriptions',
  'externalEvent.agent.subscribe',
  'externalEvent.agent.unsubscribe',
  'externalEvent.get',
  'externalEvent.listDeliveries',
  'externalEvent.listSubscriptions',
  'externalEvent.subscribe',
  'externalEvent.unsubscribe',
  'inactivity.config.get',
  'inactivity.config.set',
  'inactivity.config.setEnabled',
  'inactivity.runNow',
  'nodeAgent.restore',
  'subscribe_pr_events',
] as const;
