export const FORGE_OPERATION_NAMES = [
  'forge.episode.create',
  'forge.episode.update',
  'forge.evidence.attach',
  'forge.lesson.update',
  'forge.metric.add',
  'forge.proposal.create',
  'forge.proposal.createTask',
  'forge.proposal.update',
  'forge.rollup.apply',
  'forge.scope.create',
  'forge.scope.createFromGoal',
  'forge.scope.get',
  'forge.scope.list',
  'forge.scope.update',
] as const;
