export const NEO_OPERATION_NAMES = [
  'neo.concern.cancel',
  'neo.concern.consult',
  'neo.concern.respond',
  'neo.concern.save',
  'neo.conversation.asks.read',
  'neo.draft.recover',
  'neo.message.send',
  'neo.open',
  'neo.publication.publish',
  'neo.publication.read',
  'neo.route.correct',
  'neo.rule.save',
  'neo.snapshot',
  'neo.work.cancel',
  'neo.work.close',
  'neo.work.continue',
  'neo.work.propose',
  'neo.work.report',
  'neo.work.start',
] as const;
