export const NEO_OPERATION_NAMES = [
  'neo.concern.cancel',
  'neo.concern.consult',
  'neo.concern.respond',
  'neo.concern.save',
  'neo.message.send',
  'neo.open',
  'neo.publication.publish',
  'neo.publication.read',
  'neo.snapshot',
  'neo.work.cancel',
  'neo.work.propose',
  'neo.work.report',
  'neo.work.start',
] as const;
