export const TASK_OPERATION_NAMES = [
  'task.approve',
  'task.archive',
  'task.cancel',
  'task.complete',
  'task.create',
  'task.dependencies.set',
  'task.get',
  'task.list',
  'task.members.list',
  'task.message.send',
  'task.reject',
  'task.resolvePendingCompletion',
  'task.retry',
  'task.setPreferredWorkflow',
  'task.start',
  'task.submitForReview',
  'task.transition',
  'task.update',
] as const;
