export const TASK_OPERATION_NAMES = [
  'task.approve',
  'task.complete',
  'task.create',
  'task.get',
  'task.list',
  'task.members.list',
  'task.message.send',
  'task.preferredWorkflow.set',
  'task.reject',
  'task.retry',
  'task.start',
  'task.submitForReview',
  'task.transition',
  'task.update',
] as const;
