export {
  HTTP_4XX_STATUS_RE,
  HTTP_5XX_STATUS_RE,
  RETRYABLE_PROVIDER_ERROR_TEXT,
  TRANSIENT_CONNECTION_ERROR_REGEXES,
  TRANSIENT_CONNECTION_ERROR_SUBSTRINGS,
  isRetryableProviderError,
} from '@hyperneo/shared/provider/error-taxonomy';
