export const OPERATION_NAMES = [
  'externalEvent.get',
  'externalEvent.listDeliveries',
  'forge.episode.create',
  'forge.episode.update',
  'forge.evidence.attachTask',
  'forge.evidence.attachWorkflowRun',
  'forge.evidence.list',
  'forge.lesson.list',
  'forge.lesson.update',
  'forge.metric.add',
  'forge.metric.list',
  'forge.note.add',
  'forge.proposal.create',
  'forge.proposal.createTask',
  'forge.proposal.list',
  'forge.proposal.update',
  'forge.reviewBundle.list',
  'forge.rollup.apply',
  'forge.scope.create',
  'forge.scope.createFromGoal',
  'forge.scope.get',
  'forge.scope.list',
  'forge.scope.resolve',
  'forge.scope.update',
  'forge.timeline.get',
  'goal.get',
  'goal.list',
  'message.send',
  'operations.describe',
  'operations.list',
  'session.message.send',
  'task.archive',
  'task.cancel',
  'task.complete',
  'task.create',
  'task.dependencies.set',
  'task.get',
  'task.list',
  'task.members.list',
  'task.message.send',
  'task.resolvePendingCompletion',
  'task.setPreferredWorkflow',
  'task.start',
  'task.submitForReview',
  'task.transition',
  'task.update',
] as const;

export type OperationName = (typeof OPERATION_NAMES)[number];

export function isOperationName(value: string): value is OperationName {
  return (OPERATION_NAMES as readonly string[]).includes(value);
}
