export const OPERATION_NAMES = [
  'agent.create',
  'agent.get',
  'agent.list',
  'externalEvent.get',
  'externalEvent.listDeliveries',
  'forge.evidence.attachTask',
  'forge.evidence.attachWorkflowRun',
  'forge.evidence.list',
  'forge.metric.add',
  'forge.metric.list',
  'forge.note.add',
  'forge.scope.create',
  'forge.scope.createFromGoal',
  'forge.scope.get',
  'forge.scope.list',
  'forge.scope.resolve',
  'forge.scope.update',
  'forge.timeline.get',
  'goal.create',
  'goal.events.list',
  'goal.get',
  'goal.list',
  'goal.pause',
  'goal.resume',
  'goal.reviewOutcome',
  'goal.tasks.list',
  'goal.triggerTask',
  'goal.update',
  'message.send',
  'node.channels.list',
  'node.peers.list',
  'node.reachableAgents.list',
  'operations.describe',
  'operations.list',
  'schedule.create',
  'schedule.delete',
  'schedule.get',
  'schedule.list',
  'schedule.pause',
  'schedule.resume',
  'session.message.send',
  'task.archive',
  'task.cancel',
  'task.complete',
  'task.create',
  'task.dependencies.set',
  'task.get',
  'task.list',
  'task.members.list',
  'task.message.send',
  'task.resolvePendingCompletion',
  'task.retry',
  'task.setPreferredWorkflow',
  'task.start',
  'task.submitForReview',
  'task.transition',
  'task.update',
] as const;

export type OperationName = (typeof OPERATION_NAMES)[number];

export function isOperationName(value: string): value is OperationName {
  return (OPERATION_NAMES as readonly string[]).includes(value);
}
