export {
  LONG_HORIZON_OWNER_REVIEW_CONTRACT,
  LONG_HORIZON_SCHEDULING_GUARDRAIL,
} from '@hyperneo/prompts';
export const LONG_HORIZON_AGENT_BUILTIN_TOOLS = [
  'Read',
  'Grep',
  'Glob',
  'Bash',
  'WebFetch',
  'WebSearch',
  'Agent',
  'Task',
  'TaskOutput',
  'TaskStop',
  'AskUserQuestion',
  'EnterPlanMode',
  'ExitPlanMode',
  'TaskCreate',
  'TaskGet',
  'TaskUpdate',
  'TaskList',
  'Skill',
  'ToolSearch',
  'CronCreate',
  'CronDelete',
  'CronList',
  'ScheduleWakeup',
  'Monitor',
] as const;
