import type { ModelInfo } from '@hyperneo/shared';

export const COPILOT_ANTHROPIC_MODELS: ModelInfo[] = [
  {
    id: 'claude-opus-4.6',
    name: 'Claude Opus 4.6 (Copilot)',
    alias: 'copilot-anthropic-opus',
    family: 'opus',
    provider: 'anthropic-copilot',
    contextWindow: 200000,
    description: 'Claude Opus 4.6 via GitHub Copilot · Native Claude Agent SDK',
    releaseDate: '2025-11-01',
    available: true,
  },
  {
    id: 'claude-sonnet-4.6',
    name: 'Claude Sonnet 4.6 (Copilot)',
    alias: 'copilot-anthropic-sonnet',
    family: 'sonnet',
    provider: 'anthropic-copilot',
    contextWindow: 200000,
    description: 'Claude Sonnet 4.6 via GitHub Copilot · Native Claude Agent SDK',
    releaseDate: '2025-11-01',
    available: true,
  },
  {
    id: 'gpt-5.3-codex',
    name: 'GPT-5.3 Codex (Copilot)',
    alias: 'copilot-anthropic-codex',
    family: 'gpt',
    provider: 'anthropic-copilot',
    contextWindow: 272000,
    description: 'GPT-5.3 Codex via GitHub Copilot · Best for coding',
    releaseDate: '2025-12-01',
    available: true,
  },
  {
    id: 'gpt-5.4',
    name: 'GPT-5.4 (Copilot)',
    alias: 'copilot-anthropic-gpt-5.4',
    family: 'gpt',
    provider: 'anthropic-copilot',
    contextWindow: 272000,
    description: 'GPT-5.4 via GitHub Copilot',
    releaseDate: '2026-01-01',
    available: true,
  },
  {
    id: 'gpt-5.5',
    name: 'GPT-5.5 (Copilot)',
    alias: 'copilot-anthropic-gpt-5.5',
    family: 'gpt',
    provider: 'anthropic-copilot',
    contextWindow: 272000,
    description: 'GPT-5.5 via GitHub Copilot',
    releaseDate: '2026-04-01',
    available: true,
  },
  {
    id: 'gemini-3.1-pro-preview',
    name: 'Gemini 3.1 Pro (Copilot)',
    alias: 'copilot-anthropic-gemini',
    family: 'gemini',
    provider: 'anthropic-copilot',
    contextWindow: 128000,
    description: 'Gemini 3.1 Pro Preview via GitHub Copilot',
    releaseDate: '2025-11-15',
    available: true,
  },
  {
    id: 'gpt-5-mini',
    name: 'GPT-5 Mini (Copilot)',
    alias: 'copilot-anthropic-mini',
    family: 'gpt',
    provider: 'anthropic-copilot',
    contextWindow: 128000,
    description: 'GPT-5 Mini via GitHub Copilot · Fast and efficient',
    releaseDate: '2025-12-01',
    available: true,
  },
];
