/**
 * Shared "merge the PR" post-approval instructions template.
 *
 * Delivered to the PR Merger post-approval session by `PostApprovalRouter`
 * when a workflow declares `postApproval.targetAgent = 'merger'`. Template
 * tokens follow the §1.6 grammar evaluated by
 * `post-approval-template.ts:interpolatePostApprovalTemplate`. Recognised tokens:
 *
 *   - `{{pr_url}}`          — signalled by the end node via
 *                             `send_message(task-agent, …, data:{ pr_url })`.
 *   - `{{approval_source}}` — `'human' | 'agent'` (from `SpaceApprovalSource`).
 *   - `{{workspace_path}}`  — absolute path of the Space checkout (for step 5).
 *
 * Post-approval redesign: the Merger's only job is to MERGE. If `gh pr merge`
 * fails for any reason (conflict, failing check, missing approval, permissions,
 * merge queue, …), the Merger does NOT self-diagnose or self-approve — it has no
 * review authority. It captures the blocker reasons and reports them to the
 * Reviewer over the ungated `Post-Approval → Review` channel; the Reviewer
 * re-checks, coordinates the coder (a coder fix-push changes the head), re-
 * approves the new head on GitHub, and signals the Merger to continue over
 * `Review → Post-Approval`. The Merger then re-verifies (approval covers the
 * current head, CI, review threads) and retries. This collapses the former
 * conflict loop and Category A–F self-diagnosis into one uniform "report to
 * Reviewer" path; the Reviewer is the re-approval authority. Cycle-cap
 * exhaustion or an unresolvable blocker escalates to space-agent via the
 * `merge_blocked` artifact + message. The `Post-Approval ↔ Review` channels are
 * added to the built-in workflows in `built-in-workflows.ts` and backfilled onto
 * existing Spaces by migration 171.
 *
 * The runtime appends the universal `mark_complete` instruction in
 * `PostApprovalRouter`; keep this workflow data focused on PR-specific work.
 */
export const PR_MERGE_POST_APPROVAL_INSTRUCTIONS: string = [
  'The task has been approved. Your job is to merge PR {{pr_url}}.',
  '',
  'Approval source: {{approval_source}}.',
  'You are the Merger. Your ONLY job is to merge the PR. You have NO review',
  'authority — never approve, never push commits, never resolve review threads.',
  'If the merge fails, report the blockers to the Reviewer and wait.',
  '',
  'Steps:',
  '1. Verify the PR is still open and passes CI, and capture the base branch it merges into:',
  '     gh pr view {{pr_url}} --json state,mergeStateStatus,statusCheckRollup',
  '     gh pr checks {{pr_url}}',
  '     BASE=$(gh pr view {{pr_url}} --json baseRefName --jq .baseRefName)',
  '   BASE is the branch this PR merges INTO (its baseRefName — NOT the repo default, which',
  '   can differ, e.g. a release branch). Use $BASE everywhere below instead of a hard-coded',
  '   branch name: this built-in runs against arbitrary repos (dev/main/master/...). $BASE is a',
  '   shell variable — in tool-call payloads (send_message/save_artifact) substitute its actual',
  '   value (shown as <base branch>), never the literal "$BASE". Each Bash tool call runs in a',
  '   fresh shell, so $BASE does NOT persist across calls — re-derive it at the top of any later',
  '   command block that uses it (the gh pr view call is idempotent).',
  '   If state is MERGED, the merge already happened (possibly in a prior session). Record an',
  '   audit artifact, then perform step 5 ONLY (fast-forward the root repository — a restart',
  '   after merge must still sync it, or the root checkout stays stale and every later task',
  '   branched from it inherits the stale base branch), then exit. Do NOT redo steps 2–4 and',
  '   do NOT save the step-6 merge artifact (no merge happened in this session).',
  '2. Verify all GitHub review conversations are resolved before merging:',
  '   Extract <host>, <owner>, <repo>, and <number> from {{pr_url}} before running the query',
  '   (format: https://<host>/<owner>/<repo>/pull/<number>).',
  "     gh api graphql --hostname <host> -f query='query($owner:String!,$name:String!,$number:Int!,$cursor:String){repository(owner:$owner,name:$name){pullRequest(number:$number){reviewThreads(first:100,after:$cursor){nodes{id isResolved comments(first:20){nodes{url author{login} body createdAt}}} pageInfo{hasNextPage endCursor}}}}}' -f owner=<owner> -f name=<repo> -F number=<number>",
  '   If pageInfo.hasNextPage is true, paginate using the endCursor until all pages',
  '   have been fetched. Do NOT stop at the first page — unresolved threads may exist',
  '   beyond page 1.',
  '   If any reviewThread has isResolved=false, do NOT merge. Instead, request',
  '   coder follow-up for those thread URLs and wait for them to be resolved.',
  '   Auto-merging or auto-resolving review conversations is NOT allowed.',
  '3. Merge:',
  '     gh pr merge {{pr_url}} --squash',
  '   A zero exit does NOT always mean merged — on a merge-queue-required base it',
  '   only ENQUEUES the PR. Before step 4, re-query until the PR `state` is MERGED:',
  '     gh pr view {{pr_url}} --json state --jq .state',
  '   MERGED -> step 4. Still open but queued/processing -> keep re-querying. If',
  '   the queue entry is removed or its merge-group check fails (PR open, never',
  '   MERGED), treat that as a failure and report it to the Reviewer per 3b.',
  '   If `gh pr merge` FAILS outright (non-zero exit) for any reason (conflict,',
  '   failing check, missing approval, permissions, merge queue, etc.) — do NOT',
  '   do NOT post any review (you have NO review authority). Report the blocker',
  '   to the Reviewer, who re-checks, coordinates the coder if needed, re-approves',
  '   the head, and tells you to continue. The Reviewer is the re-approval',
  '   authority; you never approve.',
  '   a. Capture WHY it failed — the `gh pr merge` failure output plus a fresh',
  '      state snapshot:',
  '        gh pr view {{pr_url}} --json state,mergeable,mergeStateStatus,headRefOid,reviewDecision',
  '        gh pr checks {{pr_url}}',
  '      (mergeStateStatus hints: BLOCKED = a branch-protection / ruleset rule;',
  '      BEHIND = head needs a rebase onto $BASE; UNSTABLE = a required check',
  '      pending or failing; DIRTY = merge conflict; CLEAN = mergeable, so the',
  '      blocker is permissions / merge method / merge queue; UNKNOWN = GitHub',
  '      recomputing mergeability — re-query in ~30s before reporting.)',
  '   b. Report the blockers to the Reviewer over the Post-Approval → Review',
  '      channel. Give specific, actionable reasons (conflicted file paths,',
  '      failing check names, reviewDecision, mergeStateStatus) so the Reviewer',
  '      can act without rediscovering them:',
  '        send_message(target="Review", message="<short summary>",',
  '          data: { pr_url: "{{pr_url}}", base_branch: "<base branch>",',
  '                  blockers: ["<e.g. merge conflict in src/foo.ts>",',
  '                             "<e.g. required check CI failing>",',
  '                             "<e.g. reviewDecision REVIEW_REQUIRED>"],',
  '                  headRefOid: "<current head OID at failure time>",',
  '                  reason: "merge_blocked" })',
  '      Then STOP. Do NOT approve, push, resolve threads, or run gh pr merge',
  '      again until the Reviewer tells you to continue.',
  '   c. WAIT for the Reviewer. It re-checks the PR, coordinates the coder (a',
  '      coder fix-push changes the head), re-approves the new head on GitHub,',
  '      and messages you over the Review → Post-Approval channel. Your session',
  '      stays alive while idle — the message will resume you.',
  '   d. When the Reviewer replies to continue: the head likely changed, so',
  '      re-verify from scratch — re-run step 1 (state/CI) and step 2 (unresolved',
  '      review threads), and confirm a review now COVERS the current head — its',
  '      `commit_id` equals the current headRefOid (APPROVED normally; for an',
  '      own-PR where GitHub rejects self-approval, the Reviewer COMMENTED',
  '      approval-fallback review). A stale approval on the old head does NOT',
  '      cover the new one — if not covered, report again per 3b instead of',
  '      merging). Only then re-attempt',
  '      `gh pr merge {{pr_url}} --squash`. If it fails again, loop to 3a with',
  '      the fresh reasons (never reuse stale blockers or headRefOid).',
  '   e. Cycle cap / genuinely stuck: this Post-Approval ↔ Review loop is bounded',
  '      by the channel cycle budget (check `list_channels`). If a handoff is',
  '      rejected because the cap is reached, or the Reviewer reports a blocker',
  '      neither of you can resolve, escalate to space-agent (NOT merely because',
  '      merges kept failing) — record a NON-result artifact and notify:',
  '        save_artifact({ type: "merge_blocked", append: true,',
  '          summary: "Merge blocked on PR {{pr_url}} (<N> attempts, <exit>)",',
  '          data: { pr_url: "{{pr_url}}", blockers: ["..."], attempts: <N>,',
  '                  exit_reason: "<cycle_cap|unresolvable>" } })',
  '        send_message(target="space-agent", message="Merge blocked on PR',
  '          {{pr_url}} (<N> attempts, exit: <cycle_cap|unresolvable>)",',
  '          data: { pr_url: "{{pr_url}}", blockers: ["..."], attempts: <N>,',
  '                  exit_reason: "<cycle_cap|unresolvable>" })',
  '      Do NOT mark the task complete (the PR is not merged).',
  '4. Delete the PR remote branch — ONLY after a successful merge, and as a',
  '   SEPARATE command. Do NOT pass a delete flag to the merge command above;',
  '   and only delete for same-repository heads — forked PRs keep their branch',
  '   in the fork, so deleting from origin would miss or hit an unrelated',
  '   same-named branch. Assign both values with --jq, then branch on the fork',
  '   check before deleting:',
  '     HEAD_REF=$(gh pr view {{pr_url}} --json headRefName --jq .headRefName)',
  '     IS_FORK=$(gh pr view {{pr_url}} --json isCrossRepository --jq .isCrossRepository)',
  '   If IS_FORK is true, SKIP deletion. Otherwise delete the ref:',
  '     git push origin --delete "$HEAD_REF"',
  '   Branch cleanup is BEST-EFFORT: if deletion fails for any reason',
  '   (protected branch, missing delete permission, already gone), record a',
  '   NON-result warning artifact (e.g. type:"cleanup_warning") and continue —',
  '   a "result" artifact would be picked up as the task result on completion.',
  '   The PR is already merged, so do NOT let a cleanup failure block the',
  '   completion step. Do NOT delete `$BASE`.',
  '5. Sync so both this isolated worktree AND the Space checkout track the freshly-merged $BASE.',
  '   do NOT skip step b, or every later task branched from a stale checkout inherits the stale base branch.',
  '   a. In this isolated worktree, do NOT `git checkout $BASE` and do NOT switch branches — the',
  '      worktree must stay on its task branch. Just fetch:',
  '        BASE=$(gh pr view {{pr_url}} --json baseRefName --jq .baseRefName)',
  '        git fetch origin "$BASE"',
  '   b. ALSO fast-forward the separate Space checkout that future task worktrees branch from',
  '      (createTaskWorktree bases them on its HEAD). Its absolute path is supplied below as the',
  '      configured workspace — use it directly rather than inferring a path from git:',
  '      `git rev-parse --git-common-dir` resolves to the shared main-repo `.git`, whose parent is',
  '      a DIFFERENT checkout when the workspace is itself a linked worktree. Guard the checkout',
  '      before pulling:',
  '        BASE=$(gh pr view {{pr_url}} --json baseRefName --jq .baseRefName)',
  "        SPACE_WS='{{workspace_path}}'",
  '      `git pull --ff-only origin "$BASE"` fast-forwards the CURRENTLY checked-out branch, so a',
  '      checkout not on $BASE would be moved or silently left behind, and a local $BASE ahead of',
  '      origin/$BASE prints "Already up to date" while hiding stray unmerged commits that later',
  '      task worktrees would inherit. Each guard records a NON-result cleanup_warning artifact',
  '      (never a "result") and continues:',
  '        if [ "$(git -C "$SPACE_WS" rev-parse --abbrev-ref HEAD)" != "$BASE" ]; then',
  '          # checkout on a different branch — do NOT move it; warn and skip.',
  '          record a NON-result cleanup_warning artifact (space not on $BASE) and continue.',
  '        fi',
  '        git -C "$SPACE_WS" fetch origin "$BASE"',
  '        git -C "$SPACE_WS" pull --ff-only origin "$BASE"',
  '        if [ "$(git -C "$SPACE_WS" rev-parse HEAD)" != "$(git -C "$SPACE_WS" rev-parse "origin/$BASE")" ]; then',
  '          # pull said "Already up to date" but local $BASE is AHEAD of origin/$BASE — stray',
  '          # commits remain at HEAD; do NOT claim the checkout is synchronized.',
  '          record a NON-result cleanup_warning artifact (space $BASE ahead of origin/$BASE) and continue.',
  '        fi',
  '      If the pull itself fails (divergence, permissions), do NOT force it — record a',
  '      NON-result cleanup_warning artifact and continue (the PR is already merged; this',
  '      mirrors step 4 best-effort handling).',
  '6. Save an audit artifact:',
  '     save_artifact({ type: "result", append: true,',
  '                     data: { merged_pr_url, merged_at, approval_source: "{{approval_source}}" } })',
].join('\n');
