#!/bin/bash
# lib/shard-split.sh — Reusable directory-based test sharding by stable hash,
# with an optional duration-weights manifest for time-balanced packing.
#
# Why this exists
# ---------------
# When a test directory outgrows a single shard, the usual fix is to split it
# into several shards and *hand-list* which file goes where. Hand-lists rot:
# every new test file must be added by name to the right list, and any file
# someone forgets to list is silently dropped from CI (the daemon unit
# 5-space/runtime split dropped 11 real test files for months before this).
#
# This file provides one reusable mechanism instead:
#
#     "directory = shard, and split an oversized directory into N sub-shards by
#      a stable hash of the file path."
#
# A file's bucket is  stableHash(repoRootRelativePath) % N. Because the hash key
# is the path relative to the repo root, the assignment is identical on every
# developer machine and CI runner regardless of filesystem glob order, and —
# critically — adding or removing a file only ever moves that one file. Every
# existing file keeps its bucket, so re-running is stable and rebalancing is a
# one-number edit (raise N to add a shard, lower it to merge). No file list is
# ever maintained by hand.
#
# Why the optional weights manifest
# ---------------------------------
# Hash splitting balances FILE COUNT, which is a poor proxy for test duration:
# one bucket holding two 40s files next to another holding twenty 0.5s files is
# "balanced" by count yet dominates the CI critical path (measured: the daemon
# unit 5-space-runtime split landed 53s vs 146s). The weights manifest adds
# duration awareness WITHOUT giving up the no-hand-list property:
#
#   scripts/shard-weights.tsv — one "<weight-ms>\t<repo-root-relative-path>"
#   line per measured test file (generated by scripts/generate-shard-weights.ts
#   from CI junit artifacts — never edited by hand; '#' lines are comments).
#
# When a split opts into a manifest (the *_weighted entry points below), files
# present in the manifest are assigned by greedy bin-packing —
# longest-processing-time-first: sort weighted files by (weight desc, path
# asc), assign each to the currently-least-loaded bucket, ties to the lowest
# bucket index. Files NOT in the manifest keep stableHash % N, so a brand-new
# file still auto-routes with zero maintenance.
#
# Properties (the ones this file guarantees, stated explicitly):
#   - Coverage: every glob-matched file lands in exactly one bucket in
#     [0, N) — weighted via packing, unweighted via hash — so no file can be
#     silently dropped. The callers' union checks and --verify enforce it.
#   - Determinism: the same (repo state, manifest, N) yields the same
#     assignment on every machine (packing order and tie-breaks are total
#     orders; cksum is POSIX-identical everywhere).
#   - Stability: adding/removing an UNWEIGHTED file moves only that file (the
#     weighted set is untouched). Changing the weighted set or weights may
#     repack weighted files — that re-pack happens automatically at runtime, so
#     there is no stale "generated assignment" to regenerate. Raising/lowering
#     N re-packs weighted files immediately; unweighted files never move.
#
# Portability
# -----------
# Written for bash 3.2 (macOS default /bin/bash): no associative arrays, no
# globstar. The hash uses POSIX `cksum`, whose CRC algorithm is specified by
# POSIX and identical across BSD (macOS) and GNU (Linux) — so the same path
# hashes to the same integer everywhere. The packer is an awk program (awk
# associative arrays are fine; the bash 3.2 ban is on BASH associative arrays).
#
# Dependencies: bash 3.2+, cksum (POSIX), awk, sort, cut, wc.
#
# Usage
# -----
#   source scripts/lib/shard-split.sh
#
#   # Print every file in bucket <bucket_index> (0-based, must be < split_count)
#   # when a directory is split into <split_count> shards. <glob>... are bash
#   # globs relative to any base; list one glob per directory level, e.g.
#   #   dir/*.test.ts dir/sub/*.test.ts
#   shard_split_bucket <repo_root> <split_count> <bucket_index> <glob>...
#
#   # Same, but assign files listed in <manifest> by greedy duration packing
#   # (files absent from the manifest fall back to the stable hash). <manifest>
#   # must exist; a missing manifest is a loud error, never a silent fallback.
#   shard_split_bucket_weighted <repo_root> <manifest> <split_count> <bucket_index> <glob>...
#
#   # Print the total number of files matched across all globs (for audits and
#   # for choosing <split_count> when rebalancing). Mode-independent.
#   shard_split_count <repo_root> <glob>...
#
#   # Print "<bucket>\t<count>" for each bucket — a quick balance check.
#   shard_split_report <repo_root> <split_count> <glob>...
#
#   # Weighted report: "<bucket>\t<count>\t<weight-ms-sum>" per bucket — the
#   # TIME balance of the packing (only manifest-listed files contribute time).
#   shard_split_report_weighted <repo_root> <manifest> <split_count> <glob>...
#
#   # Audit a manifest for --verify: malformed lines, duplicate paths, stale
#   # paths (file gone from disk), and how many of the split's files are
#   # weighted vs hash-fallback. Returns non-zero on any hard error.
#   shard_split_weights_check <repo_root> <manifest> <split_count> <glob>...
#
# Output of shard_split_bucket / shard_split_bucket_weighted is absolute,
# repo-root-prefixed paths (e.g. /path/to/repo/packages/.../foo.test.ts),
# sorted by hash for stability, ready to pass straight to vitest.
#
# Self-test (no args to source; run directly to test the mechanism):
#   bash scripts/lib/shard-split.sh --self-test

# Compute a stable, portable integer hash for a string. POSIX `cksum` prints
# "<crc> <byte-count>"; we keep the crc. Same input → same integer everywhere.
__shard_stable_hash() {
	printf '%s' "$1" | cksum | awk '{print $1}'
}

# Internal: expand every glob and emit one line per matched file:
#   "<10-digit-hash>\t<repo-root-relative-path>"
# Lines are later sorted and de-duplicated by the callers. <bucket> is NOT
# computed here — assignment is a separate stage so hash mode and weighted
# packing can share the glob expansion.
__shard_emit() {
	local repo_root="$1"
	shift
	local globs=("$@")
	local glob f rel hash

	for glob in "${globs[@]}"; do
		# Unquoted: let bash expand the glob. The `[ -f ]` guard below skips
		# non-matches (a literal pattern left over when nothing matches) and
		# directories, so no nullglob/shopt is needed — this keeps the helper
		# free of shell-option side effects.
		for f in $glob; do
			[ -f "$f" ] || continue
			# Hash the repo-root-relative path so the key is machine-independent.
			rel="${f#"$repo_root"/}"
			hash=$(__shard_stable_hash "$rel")
			# Zero-pad the hash to 10 digits (cksum crc max is 4294967295) so
			# the upcoming `sort` orders it numerically, not lexically.
			printf '%010d\t%s\n' "$hash" "$rel"
		done
	done
}

# Internal: read "<hash>\t<rel>" lines on stdin and print
# "<hash>\t<bucket>\t<rel>" with bucket = hash % split_count.
__shard_assign_hash() {
	awk -F '\t' -v n="$1" '{ printf "%s\t%d\t%s\n", $1, $1 % n, $2 }'
}

# Internal: weighted assignment stage. Reads "<hash>\t<rel>" lines on stdin and
# prints "<hash>\t<bucket>\t<rel>\t<weight-ms>". Paths listed in the manifest
# are packed longest-processing-time-first (weight desc, path asc) into the
# least-loaded bucket (ties → lowest index); every other path keeps
# hash % split_count with weight 0. Pure awk: buffering the (small) file list
# and packing in END keeps it a single deterministic pass with no sorting fork.
__shard_assign_weighted() {
	local manifest="$1" split_count="$2"
	awk -F '\t' -v n="$split_count" -v wf="$manifest" '
		BEGIN {
			for (i = 0; i < n; i++) load[i] = 0
			if (wf != "") {
				while ((getline line < wf) > 0) {
					if (line ~ /^#/ || line ~ /^[[:space:]]*$/) continue
					split(line, a, "\t")
					weight[a[2]] = a[1] + 0
				}
				close(wf)
			}
		}
		{
			h[NR] = $1
			p[NR] = $2
			if ($2 in weight) {
				nw++
				wp[nw] = $2
				ww[nw] = weight[$2]
			}
		}
		END {
			for (i = 1; i <= nw; i++) ord[i] = i
			for (i = 1; i <= nw; i++) {
				for (j = i + 1; j <= nw; j++) {
					take = 0
					if (ww[ord[j]] > ww[ord[i]]) take = 1
					else if (ww[ord[j]] == ww[ord[i]] && wp[ord[j]] < wp[ord[i]]) take = 1
					if (take) { t = ord[i]; ord[i] = ord[j]; ord[j] = t }
				}
			}
			for (i = 1; i <= nw; i++) {
				best = 0
				for (b = 1; b < n; b++) if (load[b] < load[best]) best = b
				bucket[wp[ord[i]]] = best
				load[best] += ww[ord[i]]
			}
			for (i = 1; i <= NR; i++) {
				b = (p[i] in bucket) ? bucket[p[i]] : h[i] % n
				printf "%s\t%d\t%s\t%d\n", h[i], b, p[i], (p[i] in weight) ? weight[p[i]] : 0
			}
		}
	'
}

shard_split_bucket() {
	local repo_root="$1" split_count="$2" bucket_index="$3"
	shift 3

	# Validate arguments explicitly — this routes CI test files, so a bad value
	# should fail loudly rather than silently run an empty or wrong shard.
	local int_re='^[0-9]+$'
	[[ "$split_count" =~ $int_re ]] || { echo "shard_split_bucket: split_count must be a positive integer, got '$split_count'" >&2; return 2; }
	[[ "$bucket_index" =~ $int_re ]] || { echo "shard_split_bucket: bucket_index must be a non-negative integer, got '$bucket_index'" >&2; return 2; }
	[ "$split_count" -ge 1 ] || { echo "shard_split_bucket: split_count must be >= 1, got '$split_count'" >&2; return 2; }
	[ "$bucket_index" -lt "$split_count" ] || { echo "shard_split_bucket: bucket_index $bucket_index out of range [0,$((split_count - 1))] for split_count $split_count" >&2; return 2; }
	[ "$#" -ge 1 ] || { echo "shard_split_bucket: at least one glob is required" >&2; return 2; }

	# sort -u dedupes files matched by overlapping globs and orders by hash.
	# awk keeps only this bucket and re-prefixes the repo root for absolute paths.
	__shard_emit "$repo_root" "$@" \
		| sort -u \
		| __shard_assign_hash "$split_count" \
		| awk -F '\t' -v b="$bucket_index" -v root="$repo_root" '$2 == b { printf "%s/%s\n", root, $3 }'
}

shard_split_bucket_weighted() {
	local repo_root="$1" manifest="$2" split_count="$3" bucket_index="$4"
	shift 4

	local int_re='^[0-9]+$'
	[[ "$split_count" =~ $int_re ]] || { echo "shard_split_bucket_weighted: split_count must be a positive integer, got '$split_count'" >&2; return 2; }
	[[ "$bucket_index" =~ $int_re ]] || { echo "shard_split_bucket_weighted: bucket_index must be a non-negative integer, got '$bucket_index'" >&2; return 2; }
	[ "$split_count" -ge 1 ] || { echo "shard_split_bucket_weighted: split_count must be >= 1, got '$split_count'" >&2; return 2; }
	[ "$bucket_index" -lt "$split_count" ] || { echo "shard_split_bucket_weighted: bucket_index $bucket_index out of range [0,$((split_count - 1))] for split_count $split_count" >&2; return 2; }
	[ -n "$manifest" ] || { echo "shard_split_bucket_weighted: a manifest path is required" >&2; return 2; }
	[ -f "$manifest" ] || { echo "shard_split_bucket_weighted: manifest not found: $manifest (regenerate it with scripts/generate-shard-weights.ts, or drop the weights field from the split spec)" >&2; return 1; }
	[ "$#" -ge 1 ] || { echo "shard_split_bucket_weighted: at least one glob is required" >&2; return 2; }

	__shard_emit "$repo_root" "$@" \
		| sort -u \
		| __shard_assign_weighted "$manifest" "$split_count" \
		| awk -F '\t' -v b="$bucket_index" -v root="$repo_root" '$2 == b { printf "%s/%s\n", root, $3 }'
}

shard_split_count() {
	local repo_root="$1"
	shift
	[ "$#" -ge 1 ] || { echo "shard_split_count: at least one glob is required" >&2; return 2; }
	# The bucket assignment (hash or packed) never changes the file population:
	# counting the de-duplicated emit lines = total matched.
	__shard_emit "$repo_root" "$@" | sort -u | wc -l | tr -d ' '
}

shard_split_report() {
	local repo_root="$1" split_count="$2"
	shift 2
	[[ "$split_count" =~ ^[0-9]+$ ]] && [ "$split_count" -ge 1 ] || { echo "shard_split_report: split_count must be a positive integer, got '$split_count'" >&2; return 2; }
	[ "$#" -ge 1 ] || { echo "shard_split_report: at least one glob is required" >&2; return 2; }
	# Bucket column (field 2), tallied per bucket; emit 0 for empty buckets too.
	__shard_emit "$repo_root" "$@" \
		| sort -u \
		| __shard_assign_hash "$split_count" \
		| cut -f2 \
		| sort -n \
		| uniq -c \
		| awk -v n="$split_count" 'BEGIN { for (i = 0; i < n; i++) c[i] = 0 } { c[$2] = $1 } END { for (i = 0; i < n; i++) printf "%d\t%d\n", i, c[i] }'
}

shard_split_report_weighted() {
	local repo_root="$1" manifest="$2" split_count="$3"
	shift 3
	[[ "$split_count" =~ ^[0-9]+$ ]] && [ "$split_count" -ge 1 ] || { echo "shard_split_report_weighted: split_count must be a positive integer, got '$split_count'" >&2; return 2; }
	[ -n "$manifest" ] || { echo "shard_split_report_weighted: a manifest path is required" >&2; return 2; }
	[ -f "$manifest" ] || { echo "shard_split_report_weighted: manifest not found: $manifest" >&2; return 1; }
	[ "$#" -ge 1 ] || { echo "shard_split_report_weighted: at least one glob is required" >&2; return 2; }
	# Field 4 of the weighted assignment stage is the file's manifest weight
	# (0 for hash-fallback files), so the per-bucket sum is the packed TIME.
	__shard_emit "$repo_root" "$@" \
		| sort -u \
		| __shard_assign_weighted "$manifest" "$split_count" \
		| awk -F '\t' -v n="$split_count" 'BEGIN { for (i = 0; i < n; i++) { c[i] = 0; w[i] = 0 } } { c[$2]++; w[$2] += $4 } END { for (i = 0; i < n; i++) printf "%d\t%d\t%d\n", i, c[i], w[i] }'
}

# Audit a weights manifest for --verify. Hard errors (stderr, return 1):
#   - the manifest file is missing (a spec referencing a deleted manifest must
#     fail loudly, never silently degrade to hash-only);
#   - a data line is not exactly "<weight-ms>\t<path>" with an integer weight;
#   - the same path appears twice (last-one-wins at runtime hides the ambiguity);
#   - a path that exists in no form on disk (stale entry after a move/rename —
#     regenerate the manifest).
# Stdout: one coverage line for the split's glob set (weighted vs hash-fallback).
shard_split_weights_check() {
	local repo_root="$1" manifest="$2" split_count="$3"
	shift 3
	[[ "$split_count" =~ ^[0-9]+$ ]] && [ "$split_count" -ge 1 ] || { echo "shard_split_weights_check: split_count must be a positive integer, got '$split_count'" >&2; return 2; }
	[ "$#" -ge 1 ] || { echo "shard_split_weights_check: at least one glob is required" >&2; return 2; }
	[ -n "$manifest" ] || { echo "shard_split_weights_check: a manifest path is required" >&2; return 2; }
	[ -f "$manifest" ] || { echo "shard_split_weights_check: manifest not found: $manifest" >&2; return 1; }

	local errors=0
	local tab=$'\t'
	local line weight path
	while IFS= read -r line; do
		case "$line" in ''|'#'*) continue ;; esac
		weight="${line%%$'\t'*}"
		path="${line#*$'\t'}"
		if [ "$path" = "$line" ] || [ -z "$path" ] || [[ "$path" == *$'\t'* ]]; then
			echo "  ERROR: manifest line is not \"<weight-ms>${tab}<path>\": $line" >&2
			errors=$((errors + 1))
			continue
		fi
		[[ "$weight" =~ ^[0-9]+$ ]] || { echo "  ERROR: manifest weight is not an integer millisecond value: $line" >&2; errors=$((errors + 1)); continue; }
		[ -e "$repo_root/$path" ] || { echo "  ERROR: manifest path no longer exists on disk (regenerate the manifest): $path" >&2; errors=$((errors + 1)); continue; }
	done < "$manifest"

	local dups dup
	dups=$(grep $'\t' "$manifest" | cut -f2 | sort | uniq -d)
	while IFS= read -r dup; do
		[ -n "$dup" ] || continue
		echo "  ERROR: manifest lists this path more than once: $dup" >&2
		errors=$((errors + 1))
	done <<< "$dups"

	local total weighted
	total=$(shard_split_count "$repo_root" "$@")
	# comm needs both sides in the SAME (lexical) order: the emit side is
	# hash-ordered before cut, so it must be re-sorted after extracting paths.
	weighted=$(comm -12 \
		<(__shard_emit "$repo_root" "$@" | cut -f2 | sort -u) \
		<(grep $'\t' "$manifest" | cut -f2 | sort -u) \
		| grep -c .)
	printf '  weights: %d/%d file(s) duration-weighted, %d hash-fallback\n' "$weighted" "$total" "$((total - weighted))"

	[ "$errors" -eq 0 ] || return 1
	return 0
}

# ─── Self-test ──────────────────────────────────────────────────────────────
# Run with: bash scripts/lib/shard-split.sh --self-test
# Exits non-zero on any failure. Uses a temp fixture tree; cleans up on exit.
__shard_self_test() {
	local failures=0
	pass() { printf '  ok   %s\n' "$1"; }
	fail() { printf '  FAIL %s\n' "$1" >&2; failures=$((failures + 1)); }

	# assert <pass-msg> <fail-msg> <test-command...>
	# Wraps a condition so the pass/fail helpers are called via a real if/else
	# (avoids the `[ A ] && pass || fail` anti-pattern, where a failing `pass`
	# would wrongly trigger `fail`).
	assert() {
		local ok_msg="$1" bad_msg="$2"
		shift 2
		if "$@"; then pass "$ok_msg"; else fail "$bad_msg"; fi
	}

	# Portable temp dir (macOS mktemp wants a -t template; GNU does not).
	local root
	root=$(mktemp -d 2>/dev/null || mktemp -d -t shardselftest) || { echo "self-test: could not create temp dir" >&2; return 1; }
	trap 'rm -rf "$root"' RETURN

	# Fixture: mirror a monorepo layout so repo-root-relative paths are realistic.
	mkdir -p "$root/packages/x/tests/runtime/sub"
	local f
	for f in alpha bravo charlie delta echo foxtrot golf hotel india juliett; do
		printf 'describe(%s, () => {})\n' "$f" > "$root/packages/x/tests/runtime/$f.test.ts"
	done
	for f in kafka lima mike; do
		printf 'describe(%s, () => {})\n' "$f" > "$root/packages/x/tests/runtime/sub/$f.test.ts"
	done
	# Literal glob patterns (fully quoted); the helpers expand them internally.
	local glob1="$root/packages/x/tests/runtime/*.test.ts"
	local glob2="$root/packages/x/tests/runtime/sub/*.test.ts"

	# 1. count reports every matched file (10 top-level + 3 sub = 13).
	local total
	total=$(shard_split_count "$root" "$glob1" "$glob2")
	assert "count covers all 13 files" "count=$total, expected 13" [ "$total" -eq 13 ]

	# 2. union of all buckets == every file, with no duplicates and no gaps
	#    (the core guarantee that defeats silent file-drop regressions).
	local n=3 i=0 union union_unique bucket_files
	union=""
	while [ "$i" -lt "$n" ]; do
		bucket_files=$(shard_split_bucket "$root" "$n" "$i" "$glob1" "$glob2")
		union+="$bucket_files"$'\n'
		i=$((i + 1))
	done
	union_unique=$(printf '%s' "$union" | sed '/^$/d' | sort -u | wc -l | tr -d ' ')
	assert "3-way union covers all 13 files exactly once" "union_unique=$union_unique, expected 13" [ "$union_unique" -eq 13 ]

	# 3. report sums to the total and emits one line per bucket.
	local report sum
	report=$(shard_split_report "$root" "$n" "$glob1" "$glob2")
	sum=$(printf '%s' "$report" | awk '{s+=$2} END{print s}')
	# Count non-empty lines: $(...) strips the trailing newline, so a bare wc -l
	# undercounts by one. grep -c . counts actual data rows.
	local lines
	lines=$(printf '%s\n' "$report" | grep -c .)
	assert "report bucket counts sum to 13" "report sum=$sum, expected 13" [ "$sum" -eq 13 ]
	assert "report emits one line per bucket ($n)" "report lines=$lines, expected $n" [ "$lines" -eq "$n" ]

	# 4. determinism: the same bucket resolves identically across calls and the
	#    hash itself is a stable non-negative 32-bit integer.
	local h1 h2
	h1=$(__shard_stable_hash "packages/x/tests/runtime/alpha.test.ts")
	h2=$(__shard_stable_hash "packages/x/tests/runtime/alpha.test.ts")
	assert "hash is deterministic across calls" "hash not deterministic ($h1 vs $h2)" [ "$h1" = "$h2" ]
	if [[ "$h1" =~ ^[0-9]+$ ]] && [ "$h1" -ge 0 ] && [ "$h1" -le 4294967295 ]; then
		pass "hash is a 32-bit integer"
	else
		fail "hash out of uint32 range: '$h1'"
	fi
	local b1 b2
	b1=$(shard_split_bucket "$root" "$n" 0 "$glob1" "$glob2" | wc -l | tr -d ' ')
	b2=$(shard_split_bucket "$root" "$n" 0 "$glob1" "$glob2" | wc -l | tr -d ' ')
	assert "bucket resolution is deterministic" "bucket size differs across calls ($b1 vs $b2)" [ "$b1" = "$b2" ]

	# 5. N=1 puts every file in bucket 0.
	local one
	one=$(shard_split_bucket "$root" 1 0 "$glob1" "$glob2" | wc -l | tr -d ' ')
	assert "N=1 places all 13 files in bucket 0" "N=1 bucket0=$one, expected 13" [ "$one" -eq 13 ]

	# 6. stability under addition: adding a new file never moves an existing
	#    file's bucket (the hash-only assignment is order-independent). This is
	#    the property that lets new files auto-route with no manual edit.
	local before after moved
	before=$(shard_split_bucket "$root" "$n" 1 "$glob1" "$glob2" | sed "s|^$root/||" | sort)
	printf 'describe(november, () => {})\n' > "$root/packages/x/tests/runtime/november.test.ts"
	after=$(shard_split_bucket "$root" "$n" 1 "$glob1" "$glob2" | sed "s|^$root/||" | sort)
	# Existing files are those present before AND after; none may change presence.
	moved=$(comm -23 <(printf '%s\n' "$before") <(printf '%s\n' "$after"))
	assert "adding a file does not move existing files out of their bucket" "files dropped from bucket on add: $moved" [ -z "$moved" ]

	# 7. argument validation rejects out-of-range buckets and non-integers.
	if shard_split_bucket "$root" 2 2 "$glob1" >/dev/null 2>&1; then
		fail "bucket_index == split_count should be rejected"
	else
		pass "bucket_index == split_count is rejected"
	fi
	if shard_split_bucket "$root" 0 0 "$glob1" >/dev/null 2>&1; then
		fail "split_count=0 should be rejected"
	else
		pass "split_count=0 is rejected"
	fi

	# ── Weighted-manifest mode ──────────────────────────────────────────────
	# Fixture manifest: four files with 9s/8s/7s/6s weights. LPT into 2 buckets
	# packs 9+6=15s and 8+7=15s — the two heaviest files land apart, which
	# count-balanced hashing cannot express. november (from test 6) and the
	# other files stay hash-assigned.
	local weights="$root/shard-weights.tsv"
	{
		printf '# generated fixture\n'
		printf '9000\tpackages/x/tests/runtime/alpha.test.ts\n'
		printf '8000\tpackages/x/tests/runtime/bravo.test.ts\n'
		printf '7000\tpackages/x/tests/runtime/charlie.test.ts\n'
		printf '6000\tpackages/x/tests/runtime/delta.test.ts\n'
	} > "$weights"
	local wn=2

	# 8. the two heaviest weighted files land in different buckets.
	find_bucket() {
		local mode="$1" needle="$2" i=0 out
		while [ "$i" -lt "$wn" ]; do
			if [ "$mode" = weighted ]; then
				out=$(shard_split_bucket_weighted "$root" "$weights" "$wn" "$i" "$glob1" "$glob2")
			else
				out=$(shard_split_bucket "$root" "$wn" "$i" "$glob1" "$glob2")
			fi
			if printf '%s\n' "$out" | grep -qF "/$needle.test.ts"; then
				echo "$i"
				return 0
			fi
			i=$((i + 1))
		done
		echo -1
		return 1
	}
	local alpha_bucket bravo_bucket
	alpha_bucket=$(find_bucket weighted alpha)
	bravo_bucket=$(find_bucket weighted bravo)
	assert "heaviest files alpha and bravo pack into different buckets" "alpha=$alpha_bucket bravo=$bravo_bucket (weights 9000/8000 into $wn buckets)" [ "$alpha_bucket" != "$bravo_bucket" ]

	# 9. weighted union still covers every file exactly once (mixed packing +
	#    hash fallback cannot drop or duplicate a file).
	local wi=0 wunion wunion_unique wtotal
	wunion=""
	while [ "$wi" -lt "$wn" ]; do
		wunion+=$(shard_split_bucket_weighted "$root" "$weights" "$wn" "$wi" "$glob1" "$glob2")$'\n'
		wi=$((wi + 1))
	done
	wunion_unique=$(printf '%s' "$wunion" | sed '/^$/d' | sort -u | wc -l | tr -d ' ')
	wtotal=$(shard_split_count "$root" "$glob1" "$glob2")
	assert "weighted union covers all $wtotal files exactly once" "union_unique=$wunion_unique, expected $wtotal" [ "$wunion_unique" -eq "$wtotal" ]

	# 10. weighted report shows the packed TIME per bucket: 15000ms each.
	local wrep wsum
	wrep=$(shard_split_report_weighted "$root" "$weights" "$wn" "$glob1" "$glob2")
	wsum=$(printf '%s\n' "$wrep" | awk -F'\t' '{ if ($3 != 15000) bad=1; s+=$3 } END { print (bad ? "bad" : s) }')
	assert "weighted report shows 15s packed per bucket (30s total)" "weighted bucket sums: $(printf '%s' "$wrep" | tr '\n' ';')" [ "$wsum" = "30000" ]

	# 11. determinism of the packing: identical inputs → identical buckets.
	local wd1 wd2
	wd1=$(shard_split_bucket_weighted "$root" "$weights" "$wn" 0 "$glob1" "$glob2")
	wd2=$(shard_split_bucket_weighted "$root" "$weights" "$wn" 0 "$glob1" "$glob2")
	assert "weighted bucket resolution is deterministic" "weighted bucket differs across calls" [ "$wd1" = "$wd2" ]

	# 12. stability: adding an UNWEIGHTED file never moves a weighted file (the
	#     packed set is unchanged; the newcomer hashes into some bucket).
	local wbefore wafter wmoved
	wbefore=$(shard_split_bucket_weighted "$root" "$weights" "$wn" 0 "$glob1" "$glob2" | sort)
	printf 'describe(oscar, () => {})\n' > "$root/packages/x/tests/runtime/oscar.test.ts"
	wafter=$(shard_split_bucket_weighted "$root" "$weights" "$wn" 0 "$glob1" "$glob2" | sort)
	wmoved=$(comm -23 <(printf '%s\n' "$wbefore") <(printf '%s\n' "$wafter"))
	assert "adding an unweighted file does not move weighted files" "files dropped from bucket on add: $wmoved" [ -z "$wmoved" ]

	# 13. hash mode is untouched by the manifest's presence on disk.
	local bucket_now hash_expected
	bucket_now=$(find_bucket hash alpha)
	hash_expected=$(( $(__shard_stable_hash "packages/x/tests/runtime/alpha.test.ts") % wn ))
	assert "hash mode still uses stableHash % N with a manifest present" "alpha hash bucket=$bucket_now, expected $hash_expected" [ "$bucket_now" = "$hash_expected" ]

	# 14. a missing manifest is a loud error, not a silent hash fallback.
	if shard_split_bucket_weighted "$root" "$root/no-such-manifest.tsv" "$wn" 0 "$glob1" >/dev/null 2>&1; then
		fail "weighted bucket with a missing manifest should be rejected"
	else
		pass "weighted bucket with a missing manifest is rejected"
	fi

	# 15. weights_check: happy path reports coverage; hard failures return 1.
	if shard_split_weights_check "$root" "$weights" "$wn" "$glob1" "$glob2" >/dev/null; then
		pass "weights_check accepts a well-formed manifest"
	else
		fail "weights_check rejected a well-formed manifest"
	fi
	local bad_weights="$root/bad-weights.tsv"
	printf 'not-a-number\tpackages/x/tests/runtime/alpha.test.ts\n' > "$bad_weights"
	if shard_split_weights_check "$root" "$bad_weights" "$wn" "$glob1" "$glob2" >/dev/null 2>&1; then
		fail "weights_check should reject a non-integer weight"
	else
		pass "weights_check rejects a non-integer weight"
	fi
	printf '9000\tpackages/x/tests/runtime/gone.test.ts\n' > "$bad_weights"
	if shard_split_weights_check "$root" "$bad_weights" "$wn" "$glob1" "$glob2" >/dev/null 2>&1; then
		fail "weights_check should reject a stale path"
	else
		pass "weights_check rejects a stale path"
	fi

	echo ""
	if [ "$failures" -eq 0 ]; then
		echo "shard-split self-test: all checks passed"
		return 0
	fi
	echo "shard-split self-test: $failures CHECK(S) FAILED" >&2
	return 1
}

# When executed directly (not sourced) with --self-test, run the self-test.
# BASH_SOURCE[0] == $0 only when the file is run, not sourced.
if [[ "${1:-}" == "--self-test" && "${BASH_SOURCE[0]:-}" == "${0}" ]]; then
	__shard_self_test
	exit $?
fi
