import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, isAbsolute, join, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { discoverJunitFiles, parseJunitTimings, resolveSuitePath } from './ci-balance-report';

export type ShardSuite = 'daemon-unit' | 'daemon-online';

export interface ManifestParseResult {
  entries: Map<string, number>;
  errors: string[];
}

export function parseManifest(text: string): ManifestParseResult {
  const entries = new Map<string, number>();
  const errors: string[] = [];
  const lines = text.split('\n');
  for (let index = 0; index < lines.length; index++) {
    const line = lines[index];
    if (line === '' || line.startsWith('#')) continue;
    const firstTab = line.indexOf('\t');
    if (firstTab <= 0 || firstTab === line.length - 1 || line.includes('\t', firstTab + 1)) {
      errors.push(`line ${index + 1} is not "<weight-ms><TAB><path>": ${line}`);
      continue;
    }
    const weight = Number(line.slice(0, firstTab));
    const path = line.slice(firstTab + 1);
    if (!Number.isInteger(weight) || weight < 0) {
      errors.push(`line ${index + 1} has a non-integer weight: ${line}`);
      continue;
    }
    if (entries.has(path)) {
      errors.push(`line ${index + 1} duplicates an earlier path: ${path}`);
      continue;
    }
    entries.set(path, weight);
  }
  return { entries, errors };
}

export function renderManifest(entries: Map<string, number>): string {
  const header = [
    '# shard-weights manifest - GENERATED by scripts/generate-shard-weights.ts; do not edit by hand.',
    '# Regenerate: bun run scripts/generate-shard-weights.ts --suite <daemon-unit|daemon-online> <junit-files-or-dirs>',
    '# Format: <weight-ms><TAB><repo-root-relative-path>, sorted by path.',
    '# scripts/lib/shard-split.sh packs listed files by measured duration; files absent',
    '# here keep the stableHash assignment (regenerate to pick up new files).',
    '',
  ];
  const lines = [...entries.entries()]
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([path, weight]) => `${weight}\t${path}`);
  return `${header.join('\n')}${lines.join('\n')}${lines.length > 0 ? '\n' : ''}`;
}

export interface MergeResult {
  merged: Map<string, number>;
  updated: string[];
  kept: string[];
  staleDropped: string[];
}

export function mergeManifest(options: {
  existing: Map<string, number>;
  measured: Map<string, number>;
  covered: Set<string>;
  exists: (path: string) => boolean;
}): MergeResult {
  const merged = new Map<string, number>();
  const kept: string[] = [];
  const staleDropped: string[] = [];
  for (const [path, weight] of options.existing) {
    if (!options.exists(path)) {
      staleDropped.push(path);
      continue;
    }
    merged.set(path, weight);
    if (options.covered.has(path) && !options.measured.has(path)) kept.push(path);
  }
  const updated: string[] = [];
  for (const [path, weight] of options.measured) {
    if (!options.covered.has(path)) continue;
    merged.set(path, weight);
    updated.push(path);
  }
  updated.sort();
  kept.sort();
  staleDropped.sort();
  return { merged, updated, kept, staleDropped };
}

export function buildMeasuredFromJunit(inputs: { path: string; xml: string }[]): {
  measured: Map<string, number>;
  unresolved: string[];
} {
  const measured = new Map<string, number>();
  const unresolved: string[] = [];
  for (const input of inputs) {
    for (const suite of parseJunitTimings(input.xml).suites) {
      const resolved = resolveSuitePath(suite.name);
      if (resolved.repoPath === null) {
        unresolved.push(suite.name);
        continue;
      }
      const ms = Math.round(suite.timeSeconds * 1000);
      if (ms > (measured.get(resolved.repoPath) ?? -1)) measured.set(resolved.repoPath, ms);
    }
  }
  unresolved.sort();
  return { measured, unresolved };
}

export interface SplitSpec {
  prefix: string;
  splitCount: number;
  testRoot: string;
  globs: string[];
  weights: string | null;
  files: string[];
}

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function toPosix(path: string): string {
  return path.split(sep).join('/');
}

function runOracle(script: string, env: NodeJS.ProcessEnv = {}): string {
  return execFileSync('bash', ['-c', script], {
    cwd: repoRoot,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'inherit'],
    env: { ...process.env, ...env },
  });
}

export function listSplitSpecs(suite: ShardSuite): SplitSpec[] {
  const runner = suite === 'daemon-unit' ? 'test-daemon.sh' : 'test-online.sh';
  const specVar = suite === 'daemon-unit' ? 'HASH_SPLIT_SPECS' : 'ONLINE_HASH_SPLIT_SPECS';
  const rootVar = suite === 'daemon-unit' ? 'TEST_ROOT' : 'ONLINE_TEST_ROOT';
  const script = [
    'set -uo pipefail',
    `source scripts/${runner}`,
    `printf "%s\\t%s\\n" "testroot" "\${${rootVar}#"$REPO_ROOT"/}"`,
    `for spec in "\${${specVar}[@]}"; do`,
    '  IFS=\'|\' read -r prefix count globs weights <<< "$spec"',
    '  IFS=\';\' read -ra glob_list <<< "$globs"',
    '  for g in "${glob_list[@]}"; do',
    `    for f in \${${rootVar}}/\$g; do`,
    '      [ -f "$f" ] || continue',
    '      printf "%s\\t%s\\t%s\\t%s\\t%s\\n" "$prefix" "$count" "$globs" "$weights" "${f#"$REPO_ROOT"/}"',
    '    done',
    '  done',
    'done',
  ].join('\n');
  const output = runOracle(script);
  const byPrefix = new Map<string, SplitSpec>();
  let testRoot = '';
  for (const line of output.split('\n')) {
    if (line === '') continue;
    const fields = line.split('\t');
    if (fields[0] === 'testroot') {
      testRoot = fields[1] ?? '';
      continue;
    }
    if (fields.length !== 5) continue;
    const [prefix, count, globsField, weightsField, file] = fields;
    if (prefix === '' || file === '') continue;
    const spec = byPrefix.get(prefix) ?? {
      prefix,
      splitCount: Number(count),
      testRoot,
      globs: globsField.split(';'),
      weights: weightsField === '' ? null : weightsField,
      files: [],
    };
    if (!spec.files.includes(file)) spec.files.push(file);
    byPrefix.set(prefix, spec);
  }
  return [...byPrefix.values()].sort((a, b) => a.prefix.localeCompare(b.prefix));
}

function specAbsGlobs(spec: SplitSpec): string[] {
  return spec.globs.map((glob) => `${spec.testRoot}/${glob}`);
}

function hashBucketSums(spec: SplitSpec, weights: Map<string, number>): number[] {
  const script = [
    'set -uo pipefail',
    'source scripts/lib/shard-split.sh',
    'IFS=\';\' read -ra gs <<< "$GLOBS"',
    'b=0',
    'while [ "$b" -lt "$COUNT" ]; do',
    '  while IFS= read -r f; do',
    '    printf "%s\\t%s\\n" "$b" "${f#"$ROOT"/}"',
    '  done < <(shard_split_bucket "$ROOT" "$COUNT" "$b" "${gs[@]}")',
    '  b=$((b + 1))',
    'done',
  ].join('\n');
  const output = runOracle(script, {
    ROOT: repoRoot,
    COUNT: String(spec.splitCount),
    GLOBS: specAbsGlobs(spec).join(';'),
  });
  const sums = Array.from({ length: spec.splitCount }, () => 0);
  for (const line of output.split('\n')) {
    if (line === '') continue;
    const tab = line.indexOf('\t');
    if (tab <= 0) continue;
    const bucket = Number(line.slice(0, tab));
    const weight = weights.get(line.slice(tab + 1));
    if (Number.isInteger(bucket) && bucket >= 0 && bucket < spec.splitCount && weight) {
      sums[bucket] += weight;
    }
  }
  return sums;
}

function packedBucketSums(spec: SplitSpec, manifestPath: string): number[] {
  const script = [
    'set -uo pipefail',
    'source scripts/lib/shard-split.sh',
    'IFS=\';\' read -ra gs <<< "$GLOBS"',
    'shard_split_report_weighted "$ROOT" "$MANIFEST" "$COUNT" "${gs[@]}"',
  ].join('\n');
  const output = runOracle(script, {
    ROOT: repoRoot,
    MANIFEST: manifestPath,
    COUNT: String(spec.splitCount),
    GLOBS: specAbsGlobs(spec).join(';'),
  });
  const sums = Array.from({ length: spec.splitCount }, () => 0);
  for (const line of output.split('\n')) {
    if (line === '') continue;
    const fields = line.split('\t');
    if (fields.length !== 3) continue;
    sums[Number(fields[0])] = Number(fields[2]);
  }
  return sums;
}

function formatSeconds(ms: number): string {
  return `${(ms / 1000).toFixed(1)}s`;
}

function bucketLetter(index: number): string {
  return String.fromCharCode(97 + index);
}

function formatBuckets(sums: number[]): string {
  return sums.map((sum, index) => `${bucketLetter(index)} ${formatSeconds(sum)}`).join('  ');
}

function bucketSpread(sums: number[]): number {
  return Math.max(...sums) - Math.min(...sums);
}

interface CliOptions {
  suite: ShardSuite;
  out: string;
  dryRun: boolean;
  help: boolean;
  inputs: string[];
}

function parseArgs(args: string[]): CliOptions {
  const options: CliOptions = {
    suite: 'daemon-unit',
    out: 'scripts/shard-weights.tsv',
    dryRun: false,
    help: false,
    inputs: [],
  };
  for (let index = 0; index < args.length; index++) {
    const arg = args[index];
    if (arg === '--suite') {
      const value = args[++index];
      if (value !== 'daemon-unit' && value !== 'daemon-online') {
        throw new Error(`--suite expects daemon-unit or daemon-online, got '${value}'`);
      }
      options.suite = value;
    } else if (arg === '--out') {
      const value = args[++index];
      if (!value) throw new Error('--out expects a path');
      options.out = value;
    } else if (arg === '--dry-run') {
      options.dryRun = true;
    } else if (arg === '--help' || arg === '-h') {
      options.help = true;
    } else if (arg.startsWith('--')) {
      throw new Error(`unknown argument: ${arg}`);
    } else {
      options.inputs.push(arg);
    }
  }
  if (!options.help && options.inputs.length === 0) {
    throw new Error('no junit inputs given');
  }
  return options;
}

const usage = `usage: bun run scripts/generate-shard-weights.ts [options] <junit-file-or-dir>...

Turns CI junit per-file durations into the weights manifest consumed by
scripts/lib/shard-split.sh's duration-aware bucket packing, and prints a
before/after balance preview per opted-in split.

  <input>          junit XML file, or a directory scanned recursively for *.xml
                   (download daemon-unit-junit-* / daemon-online-junit-* artifacts
                   or point at test-results/)
  --suite <name>   which split table to regenerate: daemon-unit (default) or
                   daemon-online; only splits whose spec carries a <weights>
                   field are regenerated — others stay hash-assigned
  --out <path>     manifest to write (default scripts/shard-weights.tsv);
                   entries for files outside the targeted splits are preserved,
                   entries for deleted files are dropped
  --dry-run        print the manifest and preview without writing anything

Merge semantics: measured durations replace existing entries; a targeted file
without a measurement keeps its previous weight (on disk, absent from this junit
set); unmeasured new files get no entry and hash-fallback at runtime. The
preview's "hash today" row uses the CURRENT stable-hash buckets with the new
weights summed in; "packed" is the assignment the runner would use.`;

export interface MainSinks {
  out: (line: string) => void;
  warn: (line: string) => void;
}

export function main(
  args = process.argv.slice(2),
  sinks: MainSinks = { out: console.log, warn: console.error }
): number {
  let options: CliOptions;
  try {
    options = parseArgs(args);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    sinks.warn(`${usage}\n\nerror: ${message}`);
    return 2;
  }
  if (options.help) {
    sinks.out(usage);
    return 0;
  }

  let junitPaths: string[];
  try {
    junitPaths = discoverJunitFiles(options.inputs);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    sinks.warn(`error: ${message}`);
    return 2;
  }
  if (junitPaths.length === 0) {
    sinks.warn(`no junit XML files found under: ${options.inputs.join(', ')}`);
    return 2;
  }

  const specs = listSplitSpecs(options.suite);
  const weighted = specs.filter((spec) => spec.weights !== null);
  if (weighted.length === 0) {
    const runner = options.suite === 'daemon-unit' ? 'test-daemon.sh' : 'test-online.sh';
    sinks.warn(
      `error: no ${options.suite} split spec opts into a weights manifest (add the 4th '|' field to HASH_SPLIT_SPECS in scripts/${runner})`
    );
    return 1;
  }

  const outPath = isAbsolute(options.out)
    ? toPosix(options.out)
    : toPosix(join(repoRoot, options.out));
  const outRelative = toPosix(outPath.replace(`${toPosix(repoRoot)}/`, ''));
  for (const spec of weighted) {
    if (spec.weights !== outRelative) {
      sinks.warn(
        `warning: split '${spec.prefix}' references manifest ${spec.weights}, not ${outRelative} — regenerating it here anyway`
      );
    }
  }

  const { measured, unresolved } = buildMeasuredFromJunit(
    junitPaths.map((path) => ({ path, xml: readFileSync(path, 'utf8') }))
  );
  if (unresolved.length > 0) {
    sinks.warn(`warning: ${unresolved.length} junit suite path(s) not under a package root:`);
    for (const path of unresolved.slice(0, 10)) sinks.warn(`  - ${path}`);
  }

  const covered = new Set<string>();
  for (const spec of weighted) {
    for (const file of spec.files) covered.add(file);
  }

  const exists = (path: string) => existsSync(resolve(repoRoot, path));
  let existing = new Map<string, number>();
  if (existsSync(outPath)) {
    const parsed = parseManifest(readFileSync(outPath, 'utf8'));
    if (parsed.errors.length > 0) {
      sinks.warn(`error: existing manifest ${outRelative} is malformed:`);
      for (const message of parsed.errors) sinks.warn(`  - ${message}`);
      return 1;
    }
    existing = parsed.entries;
  }

  const merge = mergeManifest({ existing, measured, covered, exists });
  const rendered = renderManifest(merge.merged);

  const hashFallback = [...covered].filter((path) => !merge.merged.has(path)).sort();
  if (hashFallback.length > 0) {
    sinks.warn(
      `warning: ${hashFallback.length} targeted file(s) have no weight after this run — they hash-fallback:`
    );
    for (const path of hashFallback.slice(0, 10)) sinks.warn(`  - ${path}`);
  }

  let previewPath = outPath;
  let tempDir: string | null = null;
  if (options.dryRun) {
    tempDir = mkdtempSync(join(tmpdir(), 'shard-weights-'));
    previewPath = join(tempDir, 'shard-weights.tsv');
    writeFileSync(previewPath, rendered);
  } else {
    writeFileSync(outPath, rendered);
  }

  sinks.out(
    `${options.dryRun ? 'would write' : 'wrote'} ${outRelative}: ${merge.merged.size} ${merge.merged.size === 1 ? 'entry' : 'entries'} (${merge.updated.length} updated, ${merge.kept.length} kept, ${merge.staleDropped.length} stale-dropped)`
  );
  for (const spec of weighted) {
    const weightedFiles = spec.files.filter((file) => merge.merged.has(file)).length;
    const before = hashBucketSums(spec, merge.merged);
    const after = packedBucketSums(spec, previewPath);
    sinks.out(
      `preview ${spec.prefix} ${spec.splitCount}-way split, ${spec.files.length} files (${weightedFiles} weighted, ${spec.files.length - weightedFiles} hash-fallback):`
    );
    sinks.out(
      `  hash today: ${formatBuckets(before)}  (spread ${formatSeconds(bucketSpread(before))})`
    );
    sinks.out(
      `  packed:     ${formatBuckets(after)}  (spread ${formatSeconds(bucketSpread(after))})`
    );
  }

  if (tempDir !== null) rmSync(tempDir, { recursive: true, force: true });
  return 0;
}

if (import.meta.main) {
  process.exit(main());
}
