export const heroiconToLucide: Record<string, string> = {
  Bars3Icon: 'Menu',
  HomeIcon: 'Home',
  UsersIcon: 'Users',
  FolderIcon: 'Folder',
  CalendarIcon: 'Calendar',
  CalendarDaysIcon: 'CalendarDays',
  BellIcon: 'Bell',
  InboxIcon: 'Inbox',
  Cog6ToothIcon: 'Settings',
  CogIcon: 'Cog',
  SettingsIcon: 'Settings',
  PlusIcon: 'Plus',
  PlusSmallIcon: 'Plus',
  MinusIcon: 'Minus',
  XMarkIcon: 'X',
  XCircleIcon: 'XCircle',
  CheckIcon: 'Check',
  CheckCircleIcon: 'CheckCircle',
  CheckBadgeIcon: 'BadgeCheck',

  ArrowRightIcon: 'ArrowRight',
  ArrowLeftIcon: 'ArrowLeft',
  ArrowUpIcon: 'ArrowUp',
  ArrowDownIcon: 'ArrowDown',
  ArrowUpCircleIcon: 'ArrowUpCircle',
  ArrowDownCircleIcon: 'ArrowDownCircle',
  ArrowRightCircleIcon: 'ArrowRightCircle',
  ArrowLongRightIcon: 'ArrowRight',
  ArrowLongLeftIcon: 'ArrowLeft',
  ArrowPathIcon: 'ArrowRightLeft',
  ArrowUpTrayIcon: 'ArrowUpFromLine',
  ArrowDownTrayIcon: 'ArrowDownToLine',
  ChevronDownIcon: 'ChevronDown',
  ChevronLeftIcon: 'ChevronLeft',
  ChevronRightIcon: 'ChevronRight',
  ChevronUpDownIcon: 'ChevronsUpDown',

  MagnifyingGlassIcon: 'Search',
  FunnelIcon: 'Filter',
  BarsArrowUpIcon: 'BarChart3',
  HashtagIcon: 'Hash',

  UserIcon: 'User',
  UserCircleIcon: 'UserCircle',
  UserPlusIcon: 'UserPlus',
  AtSymbolIcon: 'AtSign',

  DocumentIcon: 'File',
  DocumentDuplicateIcon: 'Copy',
  DocumentPlusIcon: 'FilePlus',
  PaperClipIcon: 'Paperclip',
  PhotoIcon: 'Image',
  VideoCameraIcon: 'Video',
  CameraIcon: 'Camera',
  ChatBubbleLeftIcon: 'MessageCircle',
  ChatBubbleBottomCenterTextIcon: 'MessageSquare',
  ChatBubbleLeftEllipsisIcon: 'MessageCircleMore',

  EnvelopeIcon: 'Mail',
  EnvelopeOpenIcon: 'MailOpen',
  PhoneIcon: 'Phone',

  PencilIcon: 'Pencil',
  PencilSquareIcon: 'PencilLine',
  TrashIcon: 'Trash',
  FolderPlusIcon: 'FolderPlus',

  ChartPieIcon: 'PieChart',
  ChartBarSquareIcon: 'BarChart3',
  TableCellsIcon: 'Table',
  CubeIcon: 'Box',
  ServerIcon: 'Server',
  DatabaseIcon: 'Database',

  ExclamationCircleIcon: 'AlertCircle',
  ExclamationTriangleIcon: 'AlertTriangle',
  InformationCircleIcon: 'Info',
  QuestionMarkCircleIcon: 'HelpCircle',
  FaceSmileIcon: 'Smile',
  FaceFrownIcon: 'Frown',
  StarIcon: 'Star',

  TagIcon: 'Tag',
  BookmarkIcon: 'Bookmark',
  BriefcaseIcon: 'Briefcase',
  BanknotesIcon: 'Banknote',
  CreditCardIcon: 'CreditCard',
  CurrencyDollarIcon: 'DollarSign',
  ReceiptRefundIcon: 'Receipt',
  BaggageClaimIcon: 'BaggageClaim',

  HeartIcon: 'Heart',
  HandThumbUpIcon: 'ThumbsUp',
  FlagIcon: 'Flag',
  MegaphoneIcon: 'Megaphone',
  LockClosedIcon: 'Lock',
  LockOpenIcon: 'LockOpen',
  CommandLineIcon: 'Command',
  CodeBracketIcon: 'Code',
  CursorArrowRaysIcon: 'MousePointer',
  FingerPrintIcon: 'Fingerprint',
  GlobeAmericasIcon: 'Globe',
  GlobeAltIcon: 'Globe',
  SignalIcon: 'Signal',
  FireIcon: 'Flame',
  LifebuoyIcon: 'LifeBuoy',
  AcademicCapIcon: 'GraduationCap',
  BuildingOfficeIcon: 'Building',
  ArchiveBoxIcon: 'Archive',
  ViewColumnsIcon: 'Columns3',
  LinkIcon: 'Link',
  MapPinIcon: 'MapPin',

  EllipsisHorizontalIcon: 'Ellipsis',
  EllipsisVerticalIcon: 'EllipsisVertical',
  ClockIcon: 'Clock',

  SunIcon: 'Sun',
  MoonIcon: 'Moon',
};
